public Class A0
{//conflict
public Account createAccount(String name)  //method to create ac
{//comment source line4 src
Account QDTest= new Account();
Account QDTest1 = new Account();
Account QDTest2 = new Account();
Account QDTest3 = new Account();
Account QDTest4 = new Account();
Account QDTest5 = new Account();
Account QDTest6 = new Account();
Account QDTest7 = new Account();
Account QDTest8 = new Account();
Account QDTest9 = new Account();
Account QDTest10 = new Account();
Account QDTest11 = new Account();
Account QDTest12 = new Account();
Account QDTest13 = new Account();
Account QDTest14 = new Account();
Account QDTest15 = new Account();
Account QDTest16 = new Account();
Account QDTest17 = new Account();
Account QDTest18 = new Account();
Account QDTest19 = new Account();
Account QDTest20 = new Account();
Account QDTest21 = new Account();
Account QDTest22 = new Account();
Account QDTest23 = new Account();
Account QDTest24 = new Account();
Account QDTest25 = new Account();
Account QDTest26 = new Account();
Account QDTest27 = new Account();
Account QDTest28 = new Account();
Account QDTest29 = new Account();
Account QDTest30 = new Account();
Account QDTest31 = new Account();
Account QDTest32 = new Account();
Account QDTest33 = new Account();
Account QDTest34 = new Account();
Account QDTest35 = new Account();
Account QDTest36 = new Account();
Account QDTest37 = new Account();
Account QDTest38 = new Account();
Account QDTest39 = new Account();
Account QDTest40 = new Account();
Account QDTest41 = new Account();
return QDTest41;
}
}
