public Class A0
{//conflict test
//testetsg
//Added test comment
public Account createAccount(String name)  //method to create account
{//comment source line4 srcmodififyla
Account QDTest= new Account();
Account a01231111112331= new Account();
Account a0123111111233= new Account();
Account a0123111111= new Account(); //commentsource line2 modify1
a0123111111.Name = name; //line3
return a0123111111; //fffff src modifylast1julky22saifdfsffsdmfbdsjhbdjgfbgjfdbgkjfdgsdgfdgd
//gfdgfdgfgmds gbfhjdbgfhjdbghjfdbghfbdhjgbdfhjg abc
//shTest
}
}
