public Class A00
//
{
public Account createAccount(String name) //method to create accountsdfsdfs
{
Account sai55= new Account();
sai55.Name = name;
return sai55; 
//Modify new trial commnet fdsf mnbdsa732 cac311 dsad cxad2dsasd2 test clasd 0909321321 test clkdsadsa test ca test cldsa31
// sldkjfsldkjflsdkjflskjdflkjsdfsdf
// sldkfjsldkfjdslknbcam321 nbbca6662 test compass 21 test clsa093131 test clasd90321
// sdlfkjds fldskjflksjdflsdkjflk/dsacv,nbdsdsavcbvnbdsa878211dsadsnab32111 test clasd90321
//test989281
//98989281fdsfdsfdsfdsfdsfdsf
//test0909210921
//sajh989821s
//vdsgfdgfdgsdffgfdgfdg
}        
}